# Generated by Django 5.1.4 on 2025-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('module1', 'Module 1'), ('module2', 'Module 2')], max_length=50)),
                ('collectstatic', models.BooleanField(default=False)),
                ('script_name', models.CharField(blank=True, max_length=100, null=True)),
                ('migrations', models.BooleanField(default=False)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
    ]
